SEARCH_SERVICE: WATSON_DISCOVERY_V2
WATSON_DISCOVERY_V2:
  passages:
    enabled: True
    per_document: True
    max_per_document: 1
    fields: ['title', 'text']
    find_answers: True
    characters: 200
TEST_QUERY: "Using a dual sim card device"